apiVersion: v1
kind: ImageStream
metadata:
  name: ${MODULE_NAME}
  namespace: ${PROJECT_NAME}
  annotations:
    openshift.io/image.insecureRepository: "true"
  spec:
    dockerImageRepository: docker.io/jkvilleneuve/${MODULE_NAME}:${MODULE_TAG}
spec:
  tags:
    - name: 1.0.0
      annotations: null
      from:
        kind: DockerImage
        name: 'docker.io/jkvilleneuve/${MODULE_NAME}:${MODULE_TAG}'
      generation: 1
      importPolicy:
        insecure: true
        scheduled: true
      referencePolicy:
        type: Source