pipeline {
	agent any
	stages {
		stage('DeployToDev') {
			steps {
				sh 'echo "####################"'
				sh 'echo "tag=${MODULE_TAG}"'
				build job: 'test-service-to-dev', parameters: [string(name: 'MODULE_TAG', value: ${MODULE_TAG})]
			}
		}
	}
}
