pipeline {
    stages {
        stage('Test') {
            steps {
                sh 'echo "### start"'
                sh 'echo ${MODULE}'
                sh 'echo $PATH'
            }
        }
    }
}
