pipeline {
	agent any
	stages {
		stage('DeployToDev') {
			steps {
				sh 'echo "Run job for deploy test-service on Dev OpenShift project"'
				sh 'echo "tag=${MODULE_TAG}"'
				build job: 'test-service-to-dev', parameters: [string(name: 'MODULE_TAG', value: "${MODULE_TAG}")]
			}
		}
		stage('TestsOnDev') {
			steps {
				sh 'echo "Run script to check availability of test-service"'
				sh 'chmod -R 777 ${WORKSPACE}/openshift-deploy/test-service/dev-tests'
				sh '${WORKSPACE}/openshift-deploy/test-service/dev-tests/test-service-available.sh'
			}
		}
		stage('ApproveToTest') {
			steps {
				sh 'echo "Wait for confirmation to install on the Test"'
			}
		}
		stage('DeployToTest') {
			steps {
				sh 'echo "Run job for deploy test-service on Test OpenShift project"'
				sh 'echo "tag=${MODULE_TAG}"'
				build job: 'test-service-to-test', parameters: [string(name: 'MODULE_TAG', value: "${MODULE_TAG}")]
			}
		}
		stage('TestsOnTest') {
			steps {
				sh 'echo "Run script to get right answer from test-service"'
				sh 'chmod -R 777 ${WORKSPACE}/openshift-deploy/test-service/test-tests'
				sh '${WORKSPACE}/openshift-deploy/test-service/test-tests/test-service-answer.sh'
			}
		}
		stage('ApproveToProd') {
			steps {
				sh 'echo "Wait for confirmation to install on the Prodaction"'
			}
		}
		stage('DeployToProd') {
			steps {
				sh 'echo "Run job for deploy test-service on Production OpenShift project"'
				sh 'echo "tag=${MODULE_TAG}"'
			}
		}
	}
}
