apiVersion: v1
kind: Service
metadata:
  name: ${MODULE_NAME}
  namespace: ${PROJECT_NAME}
  labels:
    app: ${MODULE_NAME}
spec:
  ports:
  - name: ${MODULE_NAME}
    port: ${MODULE_PORT}
    protocol: TCP
  selector:
    app: ${MODULE_NAME}
    deploymentconfig: ${MODULE_NAME}
  type: LoadBalancer
