apiVersion: v1
kind: ImageStream
metadata:
  name: ${MODULE_NAME}
  namespace: ${PROJECT_NAME}
  annotations:
    openshift.io/image.insecureRepository: "true"
  spec:
    dockerImageRepository: ${DOCKER_REGISTRY}/${MODULE_NAME}:${MODULE_TAG}
spec:
  tags:
    - name: '${MODULE_TAG}'
      annotations: null
      from:
        kind: DockerImage
        name: '${DOCKER_REGISTRY}/${MODULE_NAME}:${MODULE_TAG}'
      generation: 1
      importPolicy:
        insecure: true
        scheduled: true
      referencePolicy:
        type: Source