pipeline {
	agent any
	stages {
		stage('DeployToDev') {
			steps {
				sh 'echo "Run job for deploy test-service2 on Dev OpenShift project"'
				sh 'echo "tag=${MODULE_TAG}"'
				build job: 'test-service2-to-dev', parameters: [string(name: 'MODULE_TAG', value: "${MODULE_TAG}")]
			}
		}
		stage('TestsOnDev') {
			steps {
				sh 'echo "Run script to check availability of test-service2"'
				sh 'chmod -R 777 ${WORKSPACE}/openshift-deploy/test-service2/dev-tests'
			}
		}
		stage('ApproveToTest') {
			steps {
				sh 'echo "Wait for confirmation to install on the Test"'
				input message: 'Deploy to Test?', ok: 'Deploy'
			}
		}
		stage('DeployToTest') {
			steps {
				sh 'echo "Run job for deploy test-service2 on Test OpenShift project"'
				sh 'echo "tag=${MODULE_TAG}"'
				build job: 'test-service2-to-test', parameters: [string(name: 'MODULE_TAG', value: "${MODULE_TAG}")]
			}
		}
		stage('TestsOnTest') {
			steps {
				sh 'echo "Run script to get right answer from test-service2"'
				sh 'chmod -R 777 ${WORKSPACE}/openshift-deploy/test-service2/test-tests'
			}
		}
		stage('ApproveToProd') {
			steps {
				sh 'echo "Wait for confirmation to install on the Prodaction"'
				input message: 'Deploy to Production?', ok: 'Deploy'
			}
		}
		stage('DeployToProd') {
			steps {
				sh 'echo "Run job for deploy test-service2 on Production OpenShift project"'
				sh 'echo "tag=${MODULE_TAG}"'
			}
		}
	}
}
